apiVersion: v1
kind: Service
metadata:
  name: k8stest-nodeport
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 8080
      nodePort: 32123
      protocol: TCP
  selector:
    app: k8stest