name: Build
on:
  push:
    branches: '**'
    tags-ignore: '**'

  workflow_dispatch:
    inputs:
      release-type:
        description: What type of release is this? (patch, minor, major, custom)
      custom-version:
        description: If custom release type, what version would you like to use?
jobs:
  gradle_build:
    name: Run Gradle Build
    runs-on: self-hosted
    steps:
      - name: Checkout Sources
        uses: actions/checkout@v4
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: corretto
          java-version: 17
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
      - name: Run Gradle Build
        run:  ./gradlew build

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Extract Metadata for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: cameroncai/k8stest

      - name: Copy Files
        run:  cp build/libs/*.jar .

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}